# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Linqi Zhang
tagline:          'Linqi Zhang'
description:      'I am a 3rd year PhD Student in the Department of Economics at Boston College.'
url:              http://zhanglinqi.github.io
baseurl:          /

author:
  name:           'Linqi Zhang'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           
